---


web:
    image: nginx:latest
    ports:
        - "8080:8080"
    volumes:
        - ../app:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7-fpm
    ports:
        - "9000:9000"
    volumes:
        - ../app:/code
        - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
